import * as Blockly from 'blockly/core';
import { scratchPalette } from './scratchPalette';

const motionColour = scratchPalette.motion;
const eventsColour = scratchPalette.events;
const looksColour = scratchPalette.looks;
const soundColour = scratchPalette.sound;
const controlColour = scratchPalette.control;
const sensingColour = scratchPalette.sensing;
const myBlocksColour = scratchPalette.myBlocks;
let registered = false;

export function registerCustomBlocks() {
  if (registered) {
    return;
  }

  registered = true;

  Blockly.common.defineBlocksWithJsonArray([
    {
      type: 'start_program',
      message0: 'when green flag clicked',
      nextStatement: null,
      colour: eventsColour,
      tooltip: 'The first block in your program.',
      helpUrl: '',
    },
    {
      type: 'turtle_create',
      message0: 'create turtle',
      previousStatement: null,
      nextStatement: null,
      colour: motionColour,
      tooltip: 'Make a turtle named t.',
      helpUrl: '',
    },
    {
      type: 'turtle_forward',
      message0: 'move forward %1',
      args0: [{ type: 'input_value', name: 'DISTANCE', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      colour: motionColour,
      tooltip: 'Move the turtle forward.',
      helpUrl: '',
    },
    {
      type: 'turtle_backward',
      message0: 'move backward %1',
      args0: [{ type: 'input_value', name: 'DISTANCE', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      colour: motionColour,
      tooltip: 'Move the turtle backward.',
      helpUrl: '',
    },
    {
      type: 'turtle_left',
      message0: 'turn left %1',
      args0: [{ type: 'input_value', name: 'ANGLE', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      colour: motionColour,
      tooltip: 'Turn the turtle left.',
      helpUrl: '',
    },
    {
      type: 'turtle_right',
      message0: 'turn right %1',
      args0: [{ type: 'input_value', name: 'ANGLE', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      colour: motionColour,
      tooltip: 'Turn the turtle right.',
      helpUrl: '',
    },
    {
      type: 'turtle_colour',
      message0: 'set colour %1',
      args0: [
        {
          type: 'field_dropdown',
          name: 'COLOUR',
          options: [
            ['red', 'red'],
            ['blue', 'blue'],
            ['green', 'green'],
            ['purple', 'purple'],
            ['orange', 'orange'],
            ['black', 'black'],
          ],
        },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: motionColour,
      tooltip: 'Choose the turtle pen colour.',
      helpUrl: '',
    },
    {
      type: 'turtle_pen_up',
      message0: 'pen up',
      previousStatement: null,
      nextStatement: null,
      colour: motionColour,
      tooltip: 'Lift the pen so the turtle moves without drawing.',
      helpUrl: '',
    },
    {
      type: 'turtle_pen_down',
      message0: 'pen down',
      previousStatement: null,
      nextStatement: null,
      colour: motionColour,
      tooltip: 'Put the pen down so the turtle draws.',
      helpUrl: '',
    },
    {
      type: 'character_say',
      message0: 'character says %1',
      args0: [{ type: 'field_input', name: 'MESSAGE', text: 'I can code!' }],
      previousStatement: null,
      nextStatement: null,
      colour: looksColour,
      tooltip: 'Make the stage character say something.',
      helpUrl: '',
    },
    {
      type: 'character_cheer',
      message0: 'character cheers',
      previousStatement: null,
      nextStatement: null,
      colour: looksColour,
      tooltip: 'Print a happy cheer.',
      helpUrl: '',
    },
    {
      type: 'character_jump',
      message0: 'character jumps',
      previousStatement: null,
      nextStatement: null,
      colour: looksColour,
      tooltip: 'Make a jump message for the stage.',
      helpUrl: '',
    },
    {
      type: 'say_message',
      message0: 'print %1',
      args0: [{ type: 'field_input', name: 'MESSAGE', text: 'Hello!' }],
      previousStatement: null,
      nextStatement: null,
      colour: looksColour,
      tooltip: 'Use Python print() to show a message in the output.',
      helpUrl: '',
    },
    {
      type: 'ask_question',
      message0: 'ask %1 and save as %2',
      args0: [
        { type: 'field_input', name: 'QUESTION', text: 'What is your name?' },
        { type: 'field_variable', name: 'VAR', variable: 'answer' },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: sensingColour,
      tooltip: 'Ask a question and save the answer.',
      helpUrl: '',
    },
    {
      type: 'control_if',
      message0: 'if %1 then',
      args0: [{ type: 'input_value', name: 'IF', check: 'Boolean' }],
      message1: 'do %1',
      args1: [{ type: 'input_statement', name: 'DO' }],
      previousStatement: null,
      nextStatement: null,
      colour: controlColour,
      tooltip: 'Run these blocks only when the condition is true.',
      helpUrl: '',
    },
    {
      type: 'control_if_else',
      message0: 'if %1 then',
      args0: [{ type: 'input_value', name: 'IF', check: 'Boolean' }],
      message1: 'do %1',
      args1: [{ type: 'input_statement', name: 'DO' }],
      message2: 'else %1',
      args2: [{ type: 'input_statement', name: 'ELSE' }],
      previousStatement: null,
      nextStatement: null,
      colour: controlColour,
      tooltip: 'Choose one set of blocks when the condition is true, otherwise run the else blocks.',
      helpUrl: '',
    },
    {
      type: 'control_nested_if',
      message0: 'nested if %1 then',
      args0: [{ type: 'input_value', name: 'OUTER_IF', check: 'Boolean' }],
      message1: 'do %1',
      args1: [{ type: 'input_statement', name: 'OUTER_DO' }],
      message2: 'inside, if %1 then',
      args2: [{ type: 'input_value', name: 'INNER_IF', check: 'Boolean' }],
      message3: 'do %1',
      args3: [{ type: 'input_statement', name: 'INNER_DO' }],
      previousStatement: null,
      nextStatement: null,
      colour: controlColour,
      tooltip: 'Put one if inside another if.',
      helpUrl: '',
    },
    {
      type: 'music_play',
      message0: 'play sound %1',
      args0: [
        {
          type: 'field_dropdown',
          name: 'SOUND',
          options: [
            ['Drum Beat', 'Drum Beat'],
            ['Guitar Chord', 'Guitar Chord'],
            ['Bass Intro', 'Bass Intro'],
            ['Keys Intro', 'Keys Intro'],
            ['Soft Bell', 'Soft Bell'],
            ['Chorus Hook', 'Chorus Hook'],
          ],
        },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: soundColour,
      tooltip: 'Play a music sound.',
      helpUrl: '',
    },
    {
      type: 'music_rest',
      message0: 'rest for %1 seconds',
      args0: [{ type: 'input_value', name: 'SECONDS', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      colour: soundColour,
      tooltip: 'Wait before the next sound.',
      helpUrl: '',
    },
    {
      type: 'function_define_simple',
      message0: 'define function %1 %2 do %3',
      args0: [
        { type: 'field_input', name: 'NAME', text: 'helper' },
        { type: 'input_dummy' },
        { type: 'input_statement', name: 'DO' },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: myBlocksColour,
      tooltip: 'Make a small Python function.',
      helpUrl: '',
    },
    {
      type: 'function_call_simple',
      message0: 'call function %1',
      args0: [{ type: 'field_input', name: 'NAME', text: 'helper' }],
      previousStatement: null,
      nextStatement: null,
      colour: myBlocksColour,
      tooltip: 'Run a Python function you defined.',
      helpUrl: '',
    },
  ]);
}
